import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import auth from './routes/auth.js';
import properties from './routes/properties.js';
import favorites from './routes/favorites.js';
import inquiries from './routes/inquiries.js';
import admin from './routes/admin.js';
dotenv.config();
const app=express(),PORT=Number(process.env.PORT||5000);
app.use(cors({origin:'http://localhost:5173'}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({ok:true,message:'EstateHub API is running.'}));
app.use('/api/auth',auth);
app.use('/api/properties',properties);
app.use('/api/favorites',favorites);
app.use('/api/inquiries',inquiries);
app.use('/api/admin',admin);
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Internal server error.'});});
app.listen(PORT,()=>console.log(`EstateHub backend running at http://localhost:${PORT}`));
